import {
  AlertCircle,
  ArrowLeft,
  CheckCircle2,
  Copy,
  ExternalLink,
  HandMetal,
  Info,
  Loader2,
  RefreshCw,
  ShieldAlert,
  TerminalSquare,
} from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from '@/components/ui/empty';
import { Separator } from '@/components/ui/separator';
import { useClipboard } from '@/hooks/useClipboard';
import type { PlanStatus } from '@/hooks/useSetupPlan';
import type { ApiRequestError, SetupPlan } from '@/lib/api';
import { CommandBlock } from './CommandBlock';

interface PlanViewProps {
  status: PlanStatus;
  plan: SetupPlan | null;
  error: ApiRequestError | null;
  onBack: () => void;
  onRetry: () => void;
}

/**
 * Step 4 — the setup plan (PRD §20, §23, §24).
 *
 * Every outcome the resolver can produce has somewhere to be rendered here:
 * commands to run, applications the user must install themselves, and
 * applications with no verified route at all. Nothing is dropped, because a
 * plan that quietly omits part of what was asked for is worse than one that
 * admits a gap.
 *
 * The page never executes anything, and says so.
 */
export function PlanView({ status, plan, error, onBack, onRetry }: PlanViewProps) {
  return (
    <section aria-labelledby="plan-heading">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 id="plan-heading" className="text-xl font-semibold tracking-tight">
            Your setup plan
          </h2>
          {plan && (
            <p className="mt-1 text-sm text-muted-foreground">
              For {plan.environment.distro} · {plan.environment.ecosystem}
            </p>
          )}
        </div>
        <Button type="button" variant="outline" size="sm" onClick={onBack}>
          <ArrowLeft aria-hidden="true" />
          Back to selection
        </Button>
      </div>

      <div className="mt-6" aria-live="polite" aria-busy={status === 'loading'}>
        {status === 'loading' && <PlanLoading />}
        {status === 'error' && error && <PlanError error={error} onRetry={onRetry} onBack={onBack} />}
        {status === 'ready' && plan && <PlanBody plan={plan} />}
      </div>
    </section>
  );
}

function PlanLoading() {
  return (
    <div className="flex flex-col gap-3">
      <p className="flex items-center gap-2 text-sm text-muted-foreground">
        <Loader2 aria-hidden="true" className="size-4 animate-spin" />
        Resolving your selection against the catalog…
      </p>
      {/* Skeleton shaped like the result, so the layout does not jump. */}
      {[0, 1, 2].map((i) => (
        <div key={i} className="h-16 animate-pulse rounded-lg border border-border bg-muted/40" />
      ))}
    </div>
  );
}

function PlanError({
  error,
  onRetry,
  onBack,
}: {
  error: ApiRequestError;
  onRetry: () => void;
  onBack: () => void;
}) {
  const offline = error.kind === 'offline';

  return (
    <Alert variant="destructive">
      <AlertCircle />
      <AlertTitle>
        {offline ? "Couldn't reach the ConfigShell API" : 'Could not generate a plan'}
      </AlertTitle>
      <AlertDescription>
        <p>{error.message}</p>

        {offline && (
          <p className="mt-2">
            Plans are generated by the API server rather than in your browser, so it needs to
            be running. From the repository root:{' '}
            <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">pnpm dev</code>{' '}
            starts both the web app and the API.
          </p>
        )}

        {error.code === 'UNKNOWN_APPLICATION' && (
          <p className="mt-2">
            Your selection contains an application the catalog does not know about. Clearing
            the selection and choosing again will fix it.
          </p>
        )}

        <div className="mt-3 flex flex-wrap gap-2">
          {error.retryable && (
            <Button type="button" size="sm" variant="outline" onClick={onRetry}>
              <RefreshCw aria-hidden="true" />
              Try again
            </Button>
          )}
          <Button type="button" size="sm" variant="ghost" onClick={onBack}>
            Back to selection
          </Button>
        </div>
      </AlertDescription>
    </Alert>
  );
}

function PlanBody({ plan }: { plan: SetupPlan }) {
  const { state: copyAllState, copy: copyAll } = useClipboard();
  const { commands, manualSteps, unavailable, summary } = plan;
  const script = commands.map((c) => c.command).join('\n');

  if (commands.length === 0 && manualSteps.length === 0 && unavailable.length === 0) {
    return (
      <Empty className="border border-dashed">
        <EmptyHeader>
          <EmptyMedia variant="icon">
            <TerminalSquare />
          </EmptyMedia>
          <EmptyTitle>Nothing to install</EmptyTitle>
          <EmptyDescription>Select some applications and generate the plan again.</EmptyDescription>
        </EmptyHeader>
      </Empty>
    );
  }

  return (
    <div className="flex flex-col gap-6">
      <PlanSummary summary={summary} />

      {commands.length > 0 && (
        <section aria-labelledby="commands-heading">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <h3 id="commands-heading" className="text-sm font-medium">
              Run these in your terminal, in order
            </h3>
            <Button type="button" variant="outline" size="sm" onClick={() => copyAll(script)}>
              <Copy aria-hidden="true" />
              {copyAllState === 'copied' ? 'Copied' : 'Copy all'}
            </Button>
          </div>

          <p className="mt-1 text-xs text-muted-foreground">
            ConfigShell does not run these for you. Read each one before you run it —
            commands marked “Runs as root” change your system.
          </p>

          <ol className="mt-3 flex flex-col gap-3">
            {commands.map((command, index) => (
              <li key={`${command.command}-${index}`} className="flex gap-3">
                <span
                  aria-hidden="true"
                  className="mt-3 w-5 shrink-0 text-right font-mono text-xs text-muted-foreground"
                >
                  {index + 1}
                </span>
                <div className="min-w-0 flex-1">
                  <CommandBlock
                    command={command.command}
                    privileged={command.privileged}
                    summary={command.summary}
                    note={command.note}
                  />
                </div>
              </li>
            ))}
          </ol>
        </section>
      )}

      {commands.some((c) => c.stepKind === 'verify') && <VerificationNote />}

      {manualSteps.length > 0 && <ManualSteps steps={manualSteps} />}
      {unavailable.length > 0 && <UnavailableList entries={unavailable} />}

      <Separator />

      <p className="flex items-start gap-2 text-xs text-muted-foreground">
        <ShieldAlert aria-hidden="true" className="mt-0.5 size-3.5 shrink-0" />
        <span>
          {commands.length > 0 ? (
            <>
              Every command above is built from verified catalog data — ConfigShell never
              assembles one from anything you typed. Nothing on this page can execute a
              command; running them is your own deliberate act in your own terminal.
            </>
          ) : (
            <>
              ConfigShell generated no commands for this selection, and it does not invent
              ones it cannot build from verified catalog data. Nothing on this page can
              execute a command.
            </>
          )}
        </span>
      </p>
    </div>
  );
}

function PlanSummary({ summary }: { summary: SetupPlan['summary'] }) {
  const items = [
    { label: 'Installable', value: summary.installable, tone: 'text-primary' },
    { label: 'Manual', value: summary.manual, tone: 'text-foreground' },
    { label: 'No route', value: summary.unavailable, tone: 'text-muted-foreground' },
    { label: 'Need root', value: summary.privilegedCommands, tone: 'text-foreground' },
  ];

  return (
    <Card>
      <CardHeader>
        <CardTitle>
          {summary.selected} application{summary.selected === 1 ? '' : 's'} selected
        </CardTitle>
      </CardHeader>
      <CardContent>
        <dl className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          {items.map((item) => (
            <div key={item.label} className="rounded-lg bg-muted/50 px-3 py-2">
              <dt className="text-xs text-muted-foreground">{item.label}</dt>
              <dd className={`mt-0.5 text-lg font-semibold tabular-nums ${item.tone}`}>
                {item.value}
              </dd>
            </div>
          ))}
        </dl>
      </CardContent>
    </Card>
  );
}

function VerificationNote() {
  return (
    <Alert>
      <CheckCircle2 />
      <AlertTitle>How you'll know it worked</AlertTitle>
      <AlertDescription>
        The last commands check that each application landed on your{' '}
        <code className="font-mono text-xs">PATH</code>. A line of output means it is
        installed; no output means it is not. ConfigShell cannot check this for you — it has
        no access to your machine.
      </AlertDescription>
    </Alert>
  );
}

function ManualSteps({ steps }: { steps: SetupPlan['manualSteps'] }) {
  return (
    <section aria-labelledby="manual-heading">
      <h3 id="manual-heading" className="flex items-center gap-1.5 text-sm font-medium">
        <HandMetal aria-hidden="true" className="size-4" />
        You'll need to install these yourself
      </h3>
      <p className="mt-1 text-xs text-muted-foreground">
        There is no safe command to generate for these, so ConfigShell does not invent one.
      </p>

      <ul className="mt-3 flex flex-col gap-2">
        {steps.map((step) => (
          <li key={step.applicationId} className="rounded-lg border border-border bg-card p-3">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <p className="text-sm font-medium">{step.applicationName}</p>
              <Badge variant="outline">
                {step.reason === 'repository-setup-required'
                  ? 'Needs a vendor repository'
                  : 'Vendor download only'}
              </Badge>
            </div>
            <p className="mt-1 text-xs text-muted-foreground">
              {step.reason === 'repository-setup-required'
                ? "Installing it means adding the vendor's own repository to your system. ConfigShell does not generate repository-setup commands, including signing keys."
                : 'The vendor distributes it as a download rather than through a package manager.'}
            </p>
            {step.url && (
              <Button variant="link" size="sm" className="mt-1 h-auto p-0 text-xs" asChild>
                <a href={step.url} target="_blank" rel="noreferrer noopener">
                  Vendor instructions
                  <ExternalLink aria-hidden="true" className="size-3" />
                </a>
              </Button>
            )}
          </li>
        ))}
      </ul>
    </section>
  );
}

function UnavailableList({ entries }: { entries: SetupPlan['unavailable'] }) {
  return (
    <section aria-labelledby="unavailable-heading">
      <h3 id="unavailable-heading" className="flex items-center gap-1.5 text-sm font-medium">
        <Info aria-hidden="true" className="size-4" />
        No verified route for this distribution
      </h3>
      <ul className="mt-3 flex flex-col gap-2">
        {entries.map((entry) => (
          <li key={entry.applicationId} className="rounded-lg border border-dashed border-border p-3">
            <p className="text-sm font-medium">{entry.applicationName}</p>
            <p className="mt-1 text-xs text-muted-foreground">{entry.explanation}</p>
          </li>
        ))}
      </ul>
    </section>
  );
}
