import {
  AlertCircle,
  ArrowLeft,
  CheckCircle2,
  Copy,
  ExternalLink,
  Loader2,
  RefreshCw,
  ShieldAlert,
  TerminalSquare,
} from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from '@/components/ui/empty';
import { Separator } from '@/components/ui/separator';
import { useClipboard } from '@/hooks/useClipboard';
import type { PlanStatus } from '@/hooks/useSetupPlan';
import type { ApiRequestError, SetupPlan } from '@/lib/api';
import { OUTCOMES, PLAN_STATUS } from '@/components/plan/outcomes';
import { CommandBlock } from './CommandBlock';

interface PlanViewProps {
  status: PlanStatus;
  plan: SetupPlan | null;
  error: ApiRequestError | null;
  onBack: () => void;
  onRetry: () => void;
}

/**
 * Step 4 — the setup plan (PRD §20, §23, §24).
 *
 * Every outcome the resolver can produce has somewhere to be rendered here:
 * commands to run, applications the user must install themselves, and
 * applications with no verified route at all. Nothing is dropped, because a
 * plan that quietly omits part of what was asked for is worse than one that
 * admits a gap.
 *
 * The page never executes anything, and says so.
 */
export function PlanView({ status, plan, error, onBack, onRetry }: PlanViewProps) {
  return (
    <section aria-labelledby="plan-heading">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 id="plan-heading" className="text-xl font-semibold tracking-tight">
            Your setup plan
          </h2>
          {plan && (
            <p className="mt-1 text-sm text-muted-foreground">
              For {plan.environment.distro} · {plan.environment.ecosystem}
            </p>
          )}
        </div>
        <Button type="button" variant="outline" size="sm" onClick={onBack}>
          <ArrowLeft aria-hidden="true" />
          Back to selection
        </Button>
      </div>

      <div className="mt-6" aria-live="polite" aria-busy={status === 'loading'}>
        {status === 'loading' && <PlanLoading />}
        {status === 'error' && error && <PlanError error={error} onRetry={onRetry} onBack={onBack} />}
        {status === 'ready' && plan && <PlanBody plan={plan} />}
      </div>
    </section>
  );
}

function PlanLoading() {
  return (
    <div className="flex flex-col gap-3">
      <p className="flex items-center gap-2 text-sm text-muted-foreground">
        <Loader2 aria-hidden="true" className="size-4 animate-spin" />
        Resolving your selection against the catalog…
      </p>
      {/* Skeleton shaped like the result, so the layout does not jump. */}
      {[0, 1, 2].map((i) => (
        <div key={i} className="h-16 animate-pulse rounded-lg border border-border bg-muted/40" />
      ))}
    </div>
  );
}

function PlanError({
  error,
  onRetry,
  onBack,
}: {
  error: ApiRequestError;
  onRetry: () => void;
  onBack: () => void;
}) {
  const offline = error.kind === 'offline';

  return (
    <Alert variant="destructive">
      <AlertCircle />
      <AlertTitle>
        {offline ? "Couldn't reach the ConfigShell API" : 'Could not generate a plan'}
      </AlertTitle>
      <AlertDescription>
        <p>{error.message}</p>

        {offline && (
          <p className="mt-2">
            Plans are generated by the API server rather than in your browser, so it needs to
            be running. From the repository root:{' '}
            <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">pnpm dev</code>{' '}
            starts both the web app and the API.
          </p>
        )}

        {error.code === 'UNKNOWN_APPLICATION' && (
          <p className="mt-2">
            Your selection contains an application the catalog does not know about. Clearing
            the selection and choosing again will fix it.
          </p>
        )}

        <div className="mt-3 flex flex-wrap gap-2">
          {error.retryable && (
            <Button type="button" size="sm" variant="outline" onClick={onRetry}>
              <RefreshCw aria-hidden="true" />
              Try again
            </Button>
          )}
          <Button type="button" size="sm" variant="ghost" onClick={onBack}>
            Back to selection
          </Button>
        </div>
      </AlertDescription>
    </Alert>
  );
}

function PlanBody({ plan }: { plan: SetupPlan }) {
  const { state: copyAllState, copy: copyAll } = useClipboard();
  const { commands, manualSteps, unavailable } = plan;
  const script = commands.map((c) => c.command).join('\n');

  if (commands.length === 0 && manualSteps.length === 0 && unavailable.length === 0) {
    return (
      <Empty className="border border-dashed">
        <EmptyHeader>
          <EmptyMedia variant="icon">
            <TerminalSquare />
          </EmptyMedia>
          <EmptyTitle>Nothing to install</EmptyTitle>
          <EmptyDescription>Select some applications and generate the plan again.</EmptyDescription>
        </EmptyHeader>
      </Empty>
    );
  }

  return (
    <div className="flex flex-col gap-6">
      <PlanSummary plan={plan} />

      {commands.length > 0 && (
        <section aria-labelledby="commands-heading">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <h3 id="commands-heading" className="text-sm font-medium">
              Run these in your terminal, in order
            </h3>
            <Button type="button" variant="outline" size="sm" onClick={() => copyAll(script)}>
              <Copy aria-hidden="true" />
              {copyAllState === 'copied' ? 'Copied' : 'Copy all'}
            </Button>
          </div>

          <p className="mt-1 text-xs text-muted-foreground">
            ConfigShell does not run these for you. Read each one before you run it —
            commands marked “Runs as root” change your system.
          </p>

          <ol className="mt-3 flex flex-col gap-3">
            {commands.map((command, index) => (
              <li key={`${command.command}-${index}`} className="flex gap-3">
                <span
                  aria-hidden="true"
                  className="mt-3 w-5 shrink-0 text-right font-mono text-xs text-muted-foreground"
                >
                  {index + 1}
                </span>
                <div className="min-w-0 flex-1">
                  <CommandBlock
                    command={command.command}
                    privileged={command.privileged}
                    summary={command.summary}
                    note={command.note}
                  />
                </div>
              </li>
            ))}
          </ol>
        </section>
      )}

      {commands.some((c) => c.stepKind === 'verify') && <VerificationNote />}

      {manualSteps.length > 0 && <ManualSteps steps={manualSteps} />}
      {unavailable.length > 0 && <UnavailableList entries={unavailable} />}

      <Separator />

      <p className="flex items-start gap-2 text-xs text-muted-foreground">
        <ShieldAlert aria-hidden="true" className="mt-0.5 size-3.5 shrink-0" />
        <span>
          {commands.length > 0 ? (
            <>
              Every command above is built from verified catalog data — ConfigShell never
              assembles one from anything you typed. Nothing on this page can execute a
              command; running them is your own deliberate act in your own terminal.
            </>
          ) : (
            <>
              ConfigShell generated no commands for this selection, and it does not invent
              ones it cannot build from verified catalog data. Nothing on this page can
              execute a command.
            </>
          )}
        </span>
      </p>
    </div>
  );
}

function PlanSummary({ plan }: { plan: SetupPlan }) {
  const { summary } = plan;
  const status = PLAN_STATUS[plan.status];
  const StatusIcon = status.Icon;

  /*
   * Four counts, four outcomes, one presentation map. Each tile carries its
   * label and icon as well as its colour, so the distinction does not depend
   * on seeing the colour.
   */
  const tiles = [
    { outcome: 'installable' as const, value: summary.installable },
    { outcome: 'manual' as const, value: summary.manual },
    { outcome: 'unavailable' as const, value: summary.unavailable },
    { outcome: 'privileged' as const, value: summary.privilegedCommands },
  ];

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <StatusIcon aria-hidden="true" className={`size-4 shrink-0 ${status.tone}`} />
          {status.title}
        </CardTitle>
        <p className="text-sm text-muted-foreground">
          {summary.selected} application{summary.selected === 1 ? '' : 's'} selected ·{' '}
          {summary.installable} with a command · {summary.manual} manual ·{' '}
          {summary.unavailable} with no route
        </p>
      </CardHeader>
      <CardContent>
        <dl className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          {tiles.map(({ outcome, value }) => {
            const { label, Icon, text } = OUTCOMES[outcome];
            return (
              <div key={outcome} className="rounded-lg bg-muted/50 px-3 py-2">
                <dt className="flex items-center gap-1.5 text-xs text-muted-foreground">
                  <Icon aria-hidden="true" className={`size-3.5 shrink-0 ${text}`} />
                  {label}
                </dt>
                {/* A zero is not a warning: an amber "0 runs as root" draws
                    the eye to the absence of a thing worth noticing. */}
                <dd
                  className={`mt-0.5 text-lg font-semibold tabular-nums ${
                    value === 0 ? 'text-muted-foreground' : text
                  }`}
                >
                  {value}
                </dd>
              </div>
            );
          })}
        </dl>
      </CardContent>
    </Card>
  );
}

function VerificationNote() {
  return (
    <Alert>
      <CheckCircle2 />
      <AlertTitle>How you'll know it worked</AlertTitle>
      <AlertDescription>
        The last commands check that each application landed on your{' '}
        <code className="font-mono text-xs">PATH</code>. A line of output means it is
        installed; no output means it is not. ConfigShell cannot check this for you — it has
        no access to your machine.
      </AlertDescription>
    </Alert>
  );
}

function ManualSteps({ steps }: { steps: SetupPlan['manualSteps'] }) {
  const ManualIcon = OUTCOMES.manual.Icon;

  return (
    <section aria-labelledby="manual-heading">
      <h3 id="manual-heading" className="flex items-center gap-1.5 text-sm font-medium">
        <ManualIcon aria-hidden="true" className={`size-4 ${OUTCOMES.manual.text}`} />
        You'll need to install these yourself
      </h3>
      <p className="mt-1 text-xs text-muted-foreground">
        There is no safe command to generate for these, so ConfigShell does not invent one.
        Follow the vendor's own instructions.
      </p>

      <ul className="mt-3 flex flex-col gap-2">
        {steps.map((step) => (
          <li key={step.applicationId} className="rounded-lg border border-border bg-card p-3">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <p className="text-sm font-medium">{step.applicationName}</p>
              <span className="flex flex-wrap items-center gap-1.5">
                {/* The outcome first, then why — never only the reason, which
                    on its own reads like a note on something installable. */}
                <Badge variant="outline" className={OUTCOMES.manual.text}>
                  <ManualIcon aria-hidden="true" className="size-3" />
                  {OUTCOMES.manual.label}
                </Badge>
                <Badge variant="outline">
                  {step.reason === 'repository-setup-required'
                    ? 'Needs a vendor repository'
                    : 'Vendor download only'}
                </Badge>
              </span>
            </div>
            <p className="mt-1 text-xs text-muted-foreground">
              {step.reason === 'repository-setup-required'
                ? "Installing it means adding the vendor's own repository to your system. ConfigShell does not generate repository-setup commands, including signing keys."
                : 'The vendor distributes it as a download rather than through a package manager.'}
            </p>
            {step.url && (
              <Button variant="link" size="sm" className="mt-1 h-auto p-0 text-xs" asChild>
                <a href={step.url} target="_blank" rel="noreferrer noopener">
                  Vendor instructions
                  <ExternalLink aria-hidden="true" className="size-3" />
                </a>
              </Button>
            )}
          </li>
        ))}
      </ul>
    </section>
  );
}

function UnavailableList({ entries }: { entries: SetupPlan['unavailable'] }) {
  const UnavailableIcon = OUTCOMES.unavailable.Icon;

  return (
    <section aria-labelledby="unavailable-heading">
      <h3 id="unavailable-heading" className="flex items-center gap-1.5 text-sm font-medium">
        <UnavailableIcon aria-hidden="true" className={`size-4 ${OUTCOMES.unavailable.text}`} />
        No verified route for this distribution
      </h3>
      <p className="mt-1 text-xs text-muted-foreground">
        ConfigShell has no verified source for these here, so it shows no command rather
        than one that would fail.
      </p>
      <ul className="mt-3 flex flex-col gap-2">
        {entries.map((entry) => (
          <li key={entry.applicationId} className="rounded-lg border border-dashed border-border p-3">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <p className="text-sm font-medium">{entry.applicationName}</p>
              <Badge variant="outline" className={OUTCOMES.unavailable.text}>
                <UnavailableIcon aria-hidden="true" className="size-3" />
                {OUTCOMES.unavailable.label}
              </Badge>
            </div>
            <p className="mt-1 text-xs text-muted-foreground">{entry.explanation}</p>
          </li>
        ))}
      </ul>
    </section>
  );
}
